config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'converters#new'

  resource :converter, only: [:new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/converter.rb
require 'open3'

class Converter < ActiveType::Object
  attribute :source, :text
  attribute :from_syntax, :string
  attribute :output, :text

  validates :source, presence: true
  validates :from_syntax, presence: true

  after_validation :perform_conversion

  assignable_values_for :from_syntax, default: 'scss' do
    ['scss', 'sass']
  end

  def perform_conversion
    stdout_str, _error_str, status = Open3.capture3(
        'sass-convert',
        '--from',
        from_syntax,
        '--to',
        to_syntax,
        '--stdin',
        '--no-cache',
        stdin_data: source
    )

    if status.success?
      self.output = stdout_str
    else
      errors.add(:source, "Syntax error: No valid #{from_syntax.upcase} syntax.")
    end
  end

  def new_record?
    # We don't want simple_form to think this is a updatable resource
    false
  end

  private

  def to_syntax
    if from_syntax == 'scss'
      'sass'
    elsif from_syntax == 'sass'
      'scss'
    else
      raise(InvalidArgument, <<-ERROR.squish)
        Expected #{from_syntax} to be either 'sass' or 'scss', but it wasn't.
      ERROR
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/converters_controller.rb
class ConvertersController < ApplicationController
  def new
    load_converter
  end

  def create
    load_converter
    build_converter

    @converter.save
    render :new
  end

  private

  def load_converter
    @converter ||= Converter.new
  end

  def build_converter
    @converter.attributes = converter_params
  end

  def converter_params
    converter_params = params[:converter]
    converter_params ? converter_params.permit(:source, :from_syntax, :output) : {}
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/converters/index.haml
<h1>Hallo Welt</h1>

app/views/converters/new.haml
= simple_form_for @converter, url: converter_path do |form|
  = form.input :source, as: :text
  = form.input :from_syntax, collection: form.object.humanized_from_syntaxes, value_method: :value, label_method: :humanized, include_blank: false
  = form.button :submit
  %hr
  = form.input :output, as: :text, disabled: true

app/views/layouts/_navigation.haml
%nav.navbar.navbar-default.navbar-fixed-top
  .container
    .navbar-header
      = link_to 'SCSS to SASS', root_path, class: 'navbar-brand'

app/views/layouts/application.haml
!!!
%html{:lang => "en"}
  %head
    %title SCSS to SASS
    %meta{:charset => "UTF-8"}/
    %meta{:content => "Convert SCSS to SASS and vice versa.", :name => "description"}/
    %meta{:content => "SCSS, SASS", :name => "keywords"}/
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    = favicon_link_tag 'favicon.png'
  %body
    = render 'layouts/navigation'
    .container= yield